const express = require('express');
const router = express.Router({});
const AccountAdsController = require('./account-ads.controller');
const CheckTokenMiddleware = require('../../middlewares/check-token');
const CheckAccountIdMiddleWare = require('../../middlewares/check-account-id');
const CheckEmptyCampaignMiddleWare = require('../../middlewares/check-empty-campaign');

router.get('/google-ads', CheckTokenMiddleware, AccountAdsController.getListGoogleAdsOfUser);
router.post('/', CheckTokenMiddleware, AccountAdsController.addAccountAds);
router.get('/:accountId', CheckTokenMiddleware, AccountAdsController.getDetailAccountAdword);
router.get('/:accountId/original-campaigns', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.getListOriginalCampaigns);
router.post('/:accountId/ips', CheckTokenMiddleware, CheckAccountIdMiddleWare, CheckEmptyCampaignMiddleWare, AccountAdsController.handleManipulationGoogleAds);
router.get('/:accountId/ips', CheckTokenMiddleware, CheckAccountIdMiddleWare, CheckEmptyCampaignMiddleWare, AccountAdsController.getIpsInCustomBlackList);
router.post('/:accountId/auto-blocking-ip', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.autoBlockIp);
router.post('/:accountId/auto-blocking-range-ip', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.autoBlockingRangeIp);
router.post('/:accountId/auto-blocking-3g4g', CheckTokenMiddleware, CheckAccountIdMiddleWare, CheckEmptyCampaignMiddleWare, AccountAdsController.autoBlocking3g4g);
router.put('/:accountId/block-by-private-browser', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.blockByPrivateBrowser);
router.post('/:accountId/campaigns', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.addCampaignsForAAccountAds);
router.put('/:accountId/white-list', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.updateWhiteList);
router.get('/:accountId/campaigns', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.getCampaignsInDB);
router.get('/', CheckTokenMiddleware, AccountAdsController.getAccountsAds);
router.post('/connection-confirmation', CheckTokenMiddleware, AccountAdsController.connectionConfirmation);
router.get('/:accountId/report/device', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.getReportOnDevice);
router.put('/:accountId/report/device',CheckTokenMiddleware , CheckAccountIdMiddleWare, AccountAdsController.setUpCampaignsByOneDevice);
router.post('/:accountId/block-sample-ip', CheckTokenMiddleware, CheckAccountIdMiddleWare, CheckEmptyCampaignMiddleWare, AccountAdsController.blockSampleIp);
router.get('/:accountId/block-sample-ip', CheckTokenMiddleware, CheckAccountIdMiddleWare, CheckEmptyCampaignMiddleWare, AccountAdsController.getIpInSampleBlockIp);
router.post('/:accountId/unblock-sample-ip', CheckTokenMiddleware, CheckAccountIdMiddleWare, CheckEmptyCampaignMiddleWare, AccountAdsController.unblockSampleIp);
router.get('/:accountId/verify-acctached-code-domains', CheckTokenMiddleware, CheckAccountIdMiddleWare, CheckEmptyCampaignMiddleWare, AccountAdsController.verifyAcctachedCodeDomains);
router.get('/:accountId/report', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.getReportForAccount);
router.get('/:accountId/report-statistic', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.getReportStatistic);
router.get('/:accountId/report/daily-clicking', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.getDailyClicking);
router.get('/:accountId/setting', CheckTokenMiddleware, CheckAccountIdMiddleWare, CheckEmptyCampaignMiddleWare, AccountAdsController.getSettingOfAccountAds);
router.delete('/:accountId/blocked-ips', CheckTokenMiddleware, CheckAccountIdMiddleWare, CheckEmptyCampaignMiddleWare, AccountAdsController.removeIpInAutoBlackListIp);
router.get('/:accountId/report/clicking-class-d-ips', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.getIpsInfoInClassD);
router.delete('/:accountId', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.removeAccountAds);
router.get('/:accountId/ip-history', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.getIpHistory);
router.get('/:accountId/statistic-user', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.statisticUser);
router.get('/:accountId/detail-user/:id', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.detailUser);
router.post('/connect-google-ads-by-email', CheckTokenMiddleware, AccountAdsController.ConnectGoogleAdsByEmail);
router.put('/:accountId/config-step', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.updateConfigStep);
router.put('/:accountId/enabled', CheckTokenMiddleware, CheckAccountIdMiddleWare, AccountAdsController.updateDisableStatusForAccount);

module.exports = router;
