/*
* Base on link: http://www.acuriousanimal.com/2018/10/20/express-swagger-doc.html
* */

const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const options = {
	swaggerDefinition: {
		// Like the one described here: https://swagger.io/specification/#infoObject
		info: {
			title      : 'Anti spam click',
			version    : '1.0.0',
			description: 'Test Express API with autogenerated swagger doc',
			contact: {
				email: 'thewish.it@gmail.com',
				name: 'Trần Đức Huy'
			},
			schemes: 'http'
		},
		host: 'https://localhost:3000',
		basePath: '/api'
	},
	// List of files to be processes. You can also set globs './routes/*.js'
	apis             : [
		'./modules/**/*.route.js'
	],
};

const specs = swaggerJsdoc(options);

module.exports = (app) => {
	require('./documents/tags');
	app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
};
